/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dplslab_shixl_dplstee_test_TEENative */

#ifndef _Included_com_dplslab_shixl_dplstee_test_TEENative
#define _Included_com_dplslab_shixl_dplstee_test_TEENative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dplslab_shixl_dplstee_test_TEENative
 * Method:    openTEE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dplslab_shixl_dplstee_1test_TEENative_openTEE
  (JNIEnv *, jobject);

/*
 * Class:     com_dplslab_shixl_dplstee_test_TEENative
 * Method:    closeTEE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dplslab_shixl_dplstee_1test_TEENative_closeTEE
   (JNIEnv *, jobject);

/*
 * Class:     com_dplslab_shixl_dplstee_test_TEENative
 * Method:    doAction
 * Signature: (IIII[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dplslab_shixl_dplstee_1test_TEENative_doAction
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
